[package]
name = "igniter"
version = "0.1.0"
authors = ["Paolo Marino <paolomarinos@gmail.com>"]

[dependencies]
config = "*"
serde = "*"
serde_derive = "*"
clap = "2.29.1"
ctrlc = { version = "3.0", features = ["termination"] }